### PR TITLE
Append trailing slash to static asset root

### LINKED ISSUE #144: Query startup should fail when -query.static-files has no trailing slash
It turns out that `-query.static-files` requires trailing slash. Without it instead of index.html a HTTP 404 is returned and it's not clear why. It would be good to fail at startup if it's missing.

### PR DESCRIPTION
**Pull request by yurishkuro**
* Fixes #144
  * Adds trailing `/` to the path if it's missing

### CODE REVIEW

File: cmd/query/app/static_handler.go [hunk 1]
```diff
@@ -40,11 +43,21 @@ type StaticAssetsHandler struct {
 }
 
 // NewStaticAssetsHandler returns a StaticAssetsHandler
-func NewStaticAssetsHandler(staticAssetsRoot string) *StaticAssetsHandler {
+func NewStaticAssetsHandler(staticAssetsRoot string) (*StaticAssetsHandler, error) {
```
Comment (black-adder) [inline cmd/query/app/static_handler.go]: do we consider things like this a breaking api change?

File: crossdock/main.go [hunk 2]
```diff
@@ -131,18 +132,44 @@ func InitializeCollector(logger *zap.Logger) {
 
 // NewQueryService initiates the query service
 func NewQueryService(url string, logger *zap.Logger) services.QueryService {
-	cmd := exec.Command("/bin/sh", "-c", fmt.Sprintf(queryCmd,
-		"-cassandra.keyspace=jaeger -cassandra.servers=cassandra"))
-	if err := cmd.Run(); err != nil {
-		logger.Fatal("Failed to initialize query service", zap.Error(err))
-	}
+	forkCmd(
```
Comment (pavolloffay) [inline crossdock/main.go]: Why agent and collector are not using this?

Comment (yurishkuro) [inline crossdock/main.go]: Didn't want to overload the PR, only needed to diagnose query service. 

Changed other services in #247
